# Activity Controller HTTP requests

# Create happy path
POST http://localhost:8080/api/activities
Content-Type: application/json

{
  "activityDate": "2025-07-25T18:15:00",
  "activityName": "WALK",
  "petId": 6,
  "userId": 1,
  "completed": true
}


###

#Create unhappy path
POST http://localhost:8080/api/activities
Content-Type: application/json

{
  "activityDate": "2025-07-25T18:15:00",
  "activityName": "FEED",
  "petId": 6,
  "userId": 999, 
  "completed": true
}

###

#Get by id (happy path)

GET http://localhost:8080/api/activities/12

###
# Get by id unhappy path --> not found
GET http://localhost:8080/api/activities/999999


###
# List activities by pet (get all activities)

GET http://localhost:8080/api/activities/pet/4


###
# update happy path

PUT http://localhost:8080/api/activities/6
Content-Type: application/json

{
  "id": 6,
  "activityDate": "2025-07-25T18:45:00",
  "activityName": "WALK",
  "petId": 6,
  "userId": 1,
  "completed": true,
  "notes": "3 km this time"
}


###

# Unhappy update path --> id mismatch
PUT http://localhost:8080/api/activities/12
Content-Type: application/json

{
  "id": 99,  
  "activityDate": "2025-07-25T18:45:00",
  "activityName": "WALK",
  "petId": 4,
  "userId": 1,
  "completed": true
}

###
# Sample request to get all pet activities based on userId
GET http://localhost:8080/api/activities/user/4/pets-with-activities


###
# Delete happy path
DELETE http://localhost:8080/api/activities/6?userId=1

###
# Delete unhappy path
DELETE http://localhost:8080/api/activities/5?userId=999
